[tools]
## Stack
node = { version = "latest" }
pnpm = "latest"
rust = "latest"

## Tools
cargo-binstall = "latest"
"cargo:just" = "latest"
"cargo:https://github.com/tekumara/typos-lsp" = "latest"

[settings]
# Enable extra features
experimental = true
